use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'NewGrub' do
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'SwiftHEXColors'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SwiftHTTP'
end
